version: "3.9"

services:
  api:
    container_name: hublocal_api
    build: .
    ports:
    - "8000:8000"

  database:
    container_name: hublocal_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hublocal
      POSTGRES_USER: hublocal_user
      POSTGRES_PASSWORD: hublocal_user          
    